### ISSUE TITLE
soft clipping primers from BAM files using sequences

### ISSUE THREAD

**Issue by PromitaBose** [tommyau/bamclipper#3]
Hello 
Is it possible to  soft-clips gene-specific primers from BAM  files based on  primer sequences in fasta format instead of using genomic coordinates

**Comment by PromitaBose** [comment]
Additionally I only want to soft clip an aligned read if the primer sequence shows up on the read edges

**Comment by tommyau** [comment]
Currently BAMClipper soft-clips primer sequences at read edges based on BEDPE locations, which are usually derived from primer sequences in FASTA. Do you mean you have difficulties in preparing a BEDPE file from your primer sequences FASTA?

**Comment by PromitaBose** [comment]
Many thanks for your response. 
1)How do you derive the BEDPE locations from primer sequences in FASTA ?
2) Why use BEDPE locations instead of the sequences ?

**Comment by tommyau** [comment]
Primer sequences can be mapped to genomic locations using these in silico PCR tools:
- [MFEPrimer 2.0](https://github.com/quwubin/MFEprimer/wiki/Manual)
- [UCSC In-Silico PCR](http://genome.ucsc.edu/cgi-bin/hgPcr)
- [NCBI Primer-BLAST](https://www.ncbi.nlm.nih.gov/tools/primer-blast/)
Please let me know if you have difficulties in preparing the BEDPE file. And do you think it will be handy if BAMClipper includes some kind of conversion tool to convert primer sequences to BEDPE for you?

Regarding your second question, BEDPE location is preferred for performance reason. Since aligner (e.g. BWA-MEM) matches primer sequence(s) in the NGS reads to reference genome already, BAMClipper soft-clips the primers accordingly without doing the matching again (NGS read versus primer sequences).
